[package]
name = "movement-nftstrategy"
version = "1.0.0"
authors = ["Rather Labs Inc."]

[addresses]
nft_strategy_addr = "0x07e4961db940fb1aaeddd59e4b396bf36c96cf6db5b298f7d8cbeba918cd72d6"
# nft_strategy_addr = "_"

[dev-addresses]
nft_strategy_addr = "0xbeef"

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
