[package]
name = "movement-nftstrategy"
version = "1.0.0"
authors = ["Rather Labs Inc."]

[addresses]
nft_strategy_addr = "0x1ed06520719f004c44597b27ffd2f6034d2bffef050d2e2b41f8fecfa7cdeb0b"
# nft_strategy_addr = "_"

[dev-addresses]
nft_strategy_addr = "0xbeef"

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
